version: '3.9'

services:
  web:
    container_name: MEJ
    build: .
    env_file:
      - .env
    environment:
      - PORT=8000
      - NODE_ENV=production
    ports:
      - ${PORT}:8000
    command: npm start